

DEFAULT_ADDRESS = "127.0.0.1"
DEFAULT_PORT = "11111"
DEFAULT_FUTURE_SYMBOL = "HK.HSImain"

LINKED_CONTRACT_POSTFIX_MAIN = "main"
LINKED_CONTRACT_POSTFIX_CURRENT = "current"
LINKED_CONTRACT_POSTFIX_NEXT = "next"
LINKED_CONTRACT_POSTFIX_DAY = "day"

LOCAL_SAVE_FILE_NAME = "SaveLocalData.txt"
FILE_ENCODING = "utf-8"
